import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appTitle': 'Expense Tracker',
      'dashboard': 'Dashboard',
      'transactions': 'Transactions',
      'budgets': 'Budgets',
      'calculator': 'Calculator',
      'settings': 'Settings',
      'totalIncome': 'Total Income',
      'totalExpenses': 'Total Expenses',
      'netBalance': 'Net Balance',
      'thisMonth': 'This Month',
      'addTransaction': 'Add Transaction',
      'income': 'Income',
      'expense': 'Expense',
      'amount': 'Amount',
      'category': 'Category',
      'date': 'Date',
      'description': 'Description',
      'paymentMethod': 'Payment Method',
      'type': 'Type',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'filter': 'Filter',
      'sortBy': 'Sort By',
      'search': 'Search',
      'all': 'All',
      'newest': 'Newest First',
      'oldest': 'Oldest First',
      'highestAmount': 'Highest Amount',
      'lowestAmount': 'Lowest Amount',
      'setBudget': 'Set Budget',
      'budgetLimit': 'Budget Limit',
      'spent': 'Spent',
      'remaining': 'Remaining',
      'language': 'Language',
      'theme': 'Theme',
      'darkMode': 'Dark Mode',
      'lightMode': 'Light Mode',
      'currency': 'Currency',
      'exportCSV': 'Export CSV',
      'exportJSON': 'Export JSON',
      'noTransactions': 'No transactions yet',
      'transactionAdded': 'Transaction added',
      'transactionDeleted': 'Transaction deleted',
      // Categories
      'salary': 'Salary',
      'freelance': 'Freelance',
      'business': 'Business',
      'investment': 'Investment',
      'rental': 'Rental',
      'dividends': 'Dividends',
      'gift': 'Gift',
      'refund': 'Refund',
      'grant': 'Grant',
      'food': 'Food',

      'transport': 'Transport',
      'shopping': 'Shopping',
      'bills': 'Bills',
      'entertainment': 'Entertainment',
      'health': 'Health',
      'education': 'Education',
      'other': 'Other',
      // Payment Methods
      'cash': 'Cash',
      'card': 'Card',
      'bankTransfer': 'Bank Transfer',
      'digitalWallet': 'Digital Wallet',
      // Exchange Rates
      'exchangeRates': 'Exchange Rates',
      'officialRate': 'Official Rate',
      'parallelRate': 'Parallel Market Rate',
      'useParallelRates': 'Use Parallel Market Rates',
      'usingParallel': 'Using real free market rates',
      'usingOfficial': 'Using official international rates',
      'autoUpdate': 'Auto-Update',
      'lastUpdated': 'Last Updated',
      'custom': 'Custom',
      'aboutRates': 'About Exchange Rates',
      'ratesInfo':
          'Official Rates: Standard international rates\n\nParallel Market Rates: Real street/free market rates\n\n🌐 Auto-Update: Fetch latest from online sources\n\nTap any currency to manually edit rates',
      'ratesUpdated': 'Rates updated successfully',
      'updateFailed': 'Update failed',
      'manageRates': 'Manage Exchange Rates',
      'manageRatesSubtitle': 'Configure official & parallel market rates',
      'version': 'Version',
      'appDescription':
          'A comprehensive expense and income tracker with multi-language support, budget management, and beautiful data visualization.',
      'memoryClear': 'MC',
      'memoryRecall': 'MR',
      'memoryAdd': 'M+',
      'memorySubtract': 'M-',
    },
    'fr': {
      'appTitle': 'Gestionnaire de Dépenses',
      'dashboard': 'Tableau de Bord',
      'transactions': 'Transactions',
      'budgets': 'Budgets',
      'calculator': 'Calculatrice',
      'settings': 'Paramètres',
      'totalIncome': 'Revenu Total',
      'totalExpenses': 'Dépenses Totales',
      'netBalance': 'Solde Net',
      'thisMonth': 'Ce Mois',
      'addTransaction': 'Ajouter Transaction',
      'income': 'Revenu',
      'expense': 'Dépense',
      'amount': 'Montant',
      'category': 'Catégorie',
      'date': 'Date',
      'description': 'Description',
      'paymentMethod': 'Mode de Paiement',
      'type': 'Type',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'delete': 'Supprimer',
      'edit': 'Modifier',
      'filter': 'Filtrer',
      'sortBy': 'Trier Par',
      'search': 'Rechercher',
      'all': 'Tout',
      'newest': 'Plus Récent',
      'oldest': 'Plus Ancien',
      'highestAmount': 'Montant Plus Élevé',
      'lowestAmount': 'Montant Plus Bas',
      'setBudget': 'Définir Budget',
      'budgetLimit': 'Limite de Budget',
      'spent': 'Dépensé',
      'remaining': 'Restant',
      'language': 'Langue',
      'theme': 'Thème',
      'darkMode': 'Mode Sombre',
      'lightMode': 'Mode Clair',
      'currency': 'Devise',
      'exportCSV': 'Exporter CSV',
      'exportJSON': 'Exporter JSON',
      'noTransactions': 'Aucune transaction',
      'transactionAdded': 'Transaction ajoutée',
      'transactionDeleted': 'Transaction supprimée',
      'salary': 'Salaire',
      'freelance': 'Freelance',
      'business': 'Entreprise',
      'investment': 'Investissement',
      'rental': 'Location',
      'dividends': 'Dividendes',
      'gift': 'Cadeau',
      'refund': 'Remboursement',
      'grant': 'Subvention',
      'food': 'Nourriture',
      'transport': 'Transport',
      'shopping': 'Achats',
      'bills': 'Factures',
      'entertainment': 'Divertissement',
      'health': 'Santé',
      'education': 'Éducation',
      'other': 'Autre',
      'cash': 'Espèces',
      'card': 'Carte',
      'bankTransfer': 'Virement Bancaire',
      'digitalWallet': 'Portefeuille Numérique',
      'exchangeRates': 'Taux de Change',
      'officialRate': 'Taux Officiel',
      'parallelRate': 'Taux Parallèle',
      'useParallelRates': 'Utiliser Taux Parallèles',
      'usingParallel': 'Utilisation des taux du marché libre',
      'usingOfficial': 'Utilisation des taux officiels',
      'autoUpdate': 'Mise à jour auto',
      'lastUpdated': 'Dernière mise à jour',
      'custom': 'Personnalisé',
      'aboutRates': 'À propos des taux',
      'ratesInfo':
          'Taux Officiels: Taux internationaux standards\n\nTaux Parallèles: Taux réels du marché libre\n\n🌐 Auto: Récupérer les derniers taux en ligne\n\nAppuyez sur une devise pour modifier',
      'ratesUpdated': 'Taux mis à jour avec succès',
      'updateFailed': 'Échec de la mise à jour',
      'manageRates': 'Gérer les Taux de Change',
      'manageRatesSubtitle': 'Configurer les taux officiels et parallèles',
      'version': 'Version',
      'appDescription':
          'Un outil complet de suivi des dépenses et des revenus avec prise en charge multilingue, gestion budgétaire et belle visualisation des données.',
      'memoryClear': 'MC',
      'memoryRecall': 'MR',
      'memoryAdd': 'M+',
      'memorySubtract': 'M-',
    },
    'ar': {
      'appTitle': 'متتبع النفقات',
      'dashboard': 'لوحة التحكم',
      'transactions': 'المعاملات',
      'budgets': 'الميزانيات',
      'calculator': 'الحاسبة',
      'settings': 'الإعدادات',
      'totalIncome': 'إجمالي الدخل',
      'totalExpenses': 'إجمالي النفقات',
      'netBalance': 'الرصيد الصافي',
      'thisMonth': 'هذا الشهر',
      'addTransaction': 'إضافة معاملة',
      'income': 'دخل',
      'expense': 'نفقة',
      'amount': 'المبلغ',
      'category': 'الفئة',
      'date': 'التاريخ',
      'description': 'الوصف',
      'paymentMethod': 'طريقة الدفع',
      'type': 'النوع',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'edit': 'تعديل',
      'filter': 'تصفية',
      'sortBy': 'ترتيب حسب',
      'search': 'بحث',
      'all': 'الكل',
      'newest': 'الأحدث أولاً',
      'oldest': 'الأقدم أولاً',
      'highestAmount': 'أعلى مبلغ',
      'lowestAmount': 'أقل مبلغ',
      'setBudget': 'تعيين ميزانية',
      'budgetLimit': 'حد الميزانية',
      'spent': 'تم إنفاقه',
      'remaining': 'المتبقي',
      'language': 'اللغة',
      'theme': 'السمة',
      'darkMode': 'الوضع الداكن',
      'lightMode': 'الوضع الفاتح',
      'currency': 'العملة',
      'exportCSV': 'تصدير CSV',
      'exportJSON': 'تصدير JSON',
      'noTransactions': 'لا توجد معاملات',
      'transactionAdded': 'تمت إضافة المعاملة',
      'transactionDeleted': 'تم حذف المعاملة',
      'salary': 'راتب',
      'freelance': 'عمل حر',
      'business': 'عمل تجاري',
      'investment': 'استثمار',
      'rental': 'إيجار',
      'dividends': 'أرباح الأسهم',
      'gift': 'هدية',
      'refund': 'استرداد',
      'grant': 'منحة',
      'food': 'طعام',
      'transport': 'نقل',
      'shopping': 'تسوق',
      'bills': 'فواتير',
      'entertainment': 'ترفيه',
      'health': 'صحة',
      'education': 'تعليم',
      'other': 'أخرى',
      'cash': 'نقدي',
      'card': 'بطاقة',
      'bankTransfer': 'تحويل بنكي',
      'digitalWallet': 'محفظة رقمية',
      'exchangeRates': 'أسعار الصرف',
      'officialRate': 'السعر الرسمي',
      'parallelRate': 'سعر السوق الموازي',
      'useParallelRates': 'استخدام أسعار السوق الموازي',
      'usingParallel': 'استخدام أسعار السوق الحرة الحقيقية',
      'usingOfficial': 'استخدام الأسعار الدولية الرسمية',
      'autoUpdate': 'تحديث تلقائي',
      'lastUpdated': 'آخر تحديث',
      'custom': 'مخصص',
      'aboutRates': 'حول أسعار الصرف',
      'ratesInfo':
          'الأسعار الرسمية: الأسعار الدولية القياسية\n\nأسعار السوق الموازي: أسعار السوق الحرة الحقيقية\n\n🌐 تحديث تلقائي: جلب أحدث الأسعار من الإنترنت\n\nاضغط على أي عملة لتعديل الأسعار يدوياً',
      'ratesUpdated': 'تم تحديث الأسعار بنجاح',
      'updateFailed': 'فشل التحديث',
      'manageRates': 'إدارة أسعار الصرف',
      'manageRatesSubtitle': 'تكوين الأسعار الرسمية وأسعار السوق الموازي',
      'version': 'إصدار',
      'appDescription':
          'متتبع شامل للنفقات والدخل مع دعم متعدد اللغات، وإدارة الميزانية، وتصور جميل للبيانات.',
      'memoryClear': 'MC',
      'memoryRecall': 'MR',
      'memoryAdd': 'M+',
      'memorySubtract': 'M-',
    },
    'zh': {
      'appTitle': '支出追踪器',
      'dashboard': '仪表板',
      'transactions': '交易',
      'budgets': '预算',
      'calculator': '计算器',
      'settings': '设置',
      'totalIncome': '总收入',
      'totalExpenses': '总支出',
      'netBalance': '净余额',
      'thisMonth': '本月',
      'addTransaction': '添加交易',
      'income': '收入',
      'expense': '支出',
      'amount': '金额',
      'category': '类别',
      'date': '日期',
      'description': '描述',
      'paymentMethod': '支付方式',
      'type': '类型',
      'save': '保存',
      'cancel': '取消',
      'delete': '删除',
      'edit': '编辑',
      'filter': '筛选',
      'sortBy': '排序方式',
      'search': '搜索',
      'all': '全部',
      'newest': '最新优先',
      'oldest': '最旧优先',
      'highestAmount': '金额最高',
      'lowestAmount': '金额最低',
      'setBudget': '设置预算',
      'budgetLimit': '预算限额',
      'spent': '已花费',
      'remaining': '剩余',
      'language': '语言',
      'theme': '主题',
      'darkMode': '深色模式',
      'lightMode': '浅色模式',
      'currency': '货币',
      'exportCSV': '导出 CSV',
      'exportJSON': '导出 JSON',
      'noTransactions': '暂无交易',
      'transactionAdded': '交易添加成功',
      'transactionDeleted': '交易删除成功',
      'salary': '工资',
      'freelance': '自由职业',
      'business': '商业',
      'investment': '投资',
      'rental': '租赁',
      'dividends': '股息',
      'gift': '礼物',
      'refund': '退款',
      'grant': '补助金',
      'food': '食品',
      'transport': '交通',
      'shopping': '购物',
      'bills': '账单',
      'entertainment': '娱乐',
      'health': '健康',
      'education': '教育',
      'other': '其他',
      'cash': '现金',
      'card': '卡',
      'bankTransfer': '银行转账',
      'digitalWallet': '数字钱包',
      'exchangeRates': '汇率',
      'officialRate': '官方汇率',
      'parallelRate': '平行市场汇率',
      'useParallelRates': '使用平行市场汇率',
      'usingParallel': '使用真实自由市场汇率',
      'usingOfficial': '使用官方国际汇率',
      'autoUpdate': '自动更新',
      'lastUpdated': '最后更新',
      'custom': '自定义',
      'aboutRates': '关于汇率',
      'ratesInfo':
          '官方汇率：标准国际汇率\n\n平行市场汇率：真实自由市场汇率\n\n🌐 自动更新：从在线来源获取最新汇率\n\n点击任意货币手动编辑汇率',
      'ratesUpdated': '汇率更新成功',
      'updateFailed': '更新失败',
      'manageRates': '管理汇率',
      'manageRatesSubtitle': '配置官方和平行市场汇率',
      'version': '版本',
      'appDescription': '一款全面的收支追踪器，支持多语言、预算管理和精美的数据可视化。',
      'memoryClear': 'MC',
      'memoryRecall': 'MR',
      'memoryAdd': 'M+',
      'memorySubtract': 'M-',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'fr', 'ar', 'zh'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
